application.data-dir: ${DATA_DIR:~/restservice}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/bootcamp?useTimezone=true&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/bootcamp?useTimezone=true&serverTimezone=UTC
    username: root
    password: adam003
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8080
#server.error.whitelabel.enabled: false